from typing import overload

class Degrees(Double):
    def __init__(self, *args, **kwargs) -> None: ...

class Double:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, val: float) -> None: ...
    def __float__(self) -> float: ...
